name: "Docker Build & Push if Changed"
description: "Build an image and push it to GHRC if the Dockerfile changed"

runs:
  using: "composite"
  steps:
    - name: Check if File Changed
      id: check_file_changed
    - name: Make image name
      run: |
        echo "IMAGE_STUB=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v2
    - name: Login to the Registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push image
      uses: docker/build-push-action@v3.1.0
      with:
        push: true
        tags: ghcr.io/${{ env.IMAGE_STUB }}/rclone:latest
        file: "dockerfiles/Dockerfile.rclone"
        # cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_STUB }}/rclone:buildcache
        # cache-to: type=registry,ref=ghcr.io/${{ env.IMAGE_STUB }}/rclone:buildcache,mode=max