name: Build & Push Image

on:
  push:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  Check if rclone Dockerfile changed:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Changed
        id: check_if_rclone_changed
        uses: ./check_if_changed
  Build & Push rclone image:
    runs-on: ubuntu-latest
    needs: [ "Check if rclone Dockerfile changed" ]
    if: needs.check_if_rclone_changed.outputs.is_changed == 'false' }}
    steps:
      - name: Build & Push rclone image
        run: |
          echo "WOULD NOT PRODUCE IMAGE"

    # permissions:
    #   contents: read
    #   packages: write

    # steps:
    #   - name: Build and Push rclone image
    #     uses: ./docker_build_push_if_changed