name: Build & Push Proj Image

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}-proj"

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Print the image name
        run: echo "${{ env.IMAGE_NAME }}"
        