name: Build & Push Image

on:
  push:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:

  check_if_rclone_dockerfile_changed:
    name: Check if rclone Dockerfile changed
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.check_if_rclone_changed.outputs.is_changed }}
    steps:
      - uses: actions/checkout@v2
      - name: Check if Changed
        id: check_if_rclone_changed
        uses: ./check_if_changed
        with:
          file: dockerfiles/Dockerfile.rclone
      - run: echo "${{ steps.check_if_rclone_changed.outputs.is_changed }}"

  build_push_rclone_image:
    name: Build & Push rclone image
    runs-on: ubuntu-latest
    needs: [ check_if_rclone_dockerfile_changed ]
    # if: needs.check_if_rclone_dockerfile_changed.outputs.is_changed == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Make image name
        shell: bash
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY_OWNER,,}/rclone" >> ${GITHUB_ENV}
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to the Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v3.1.0
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest
          file: "dockerfiles/Dockerfile.rclone"
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.IMAGE_NAME }}:buildcache,mode=max

      # - uses: actions/checkout@v2
      # - name: Build & Push rclone image
      #   uses: ./docker_build_push
      #   with:
      #     file: dockerfiles/Dockerfile.rclone
      #     image_name: rclone
      #     token: ${{ secrets.GITHUB_TOKEN }}


    # steps:
    #   - name: Build and Push rclone image
    #     uses: ./docker_build_push_if_changed