name: Build & Push Rclone Image

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Make image name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v3.1.0
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          file: "{{defaultContext}}:dockerfiles/Dockerfile.rclone