name: Build & Push Image

on:
  push:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:

  check_if_rclone_dockerfile_changed:
    name: Check if rclone Dockerfile changed
    runs-on: ubuntu-latest
    outputs:
      is_changed: ${{ steps.check_if_rclone_changed.outputs.is_changed }}
    steps:
      - uses: actions/checkout@v2
      - name: Check if Changed
        id: check_if_rclone_changed
        uses: ./check_if_changed
        with:
          file: dockerfiles/Dockerfile.rclone
      - run: echo "${{ steps.check_if_rclone_changed.outputs.is_changed }}"

  build_push_rclone_image:
    name: Build & Push rclone image
    runs-on: ubuntu-latest
    needs: [ check_if_rclone_dockerfile_changed ]
    # if: needs.check_if_rclone_dockerfile_changed.outputs.is_changed == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Build & Push rclone image
        uses: ./docker_build_push
        with:
          file: dockerfiles/Dockerfile.rclone
          image_name: rclone

    # permissions:
    #   contents: read
    #   packages: write

    # steps:
    #   - name: Build and Push rclone image
    #     uses: ./docker_build_push_if_changed