name: Build & Push Image

on:
  push:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  Build & Push rclone image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and Push rclone image
        uses: ./docker_build_push_if_changed